--[[
Items added here provide priority strings to item drops in game, e.g.:

loot_prio = {}
loot_prio["Item"] = " - |cffc79c6eWarrior|r > |cff69ccf0Mage|r > |cfffff569Rogue|r > |cffff7d0aDruid|r > |cffabd473Hunter|r > |cff0070deShaman|r > |cffffffffPriest|r > |cff9482c9Warlock|r > |cfff58cbaPaladin|r"
...

--]]

loot_prio = {}
-- < Temple of Ahn'Qiraj >
-- The Prophet Skeram:
loot_prio["Pendant of the Qiraji Guardian"] = " - |cff9664c8No Prio|r"
loot_prio["Amulet of Foul Warding"] = " - |cff9664c8No Prio|r"
loot_prio["Beetle Scaled Wristguards"] = " - |cff9664c8No Prio|r"
loot_prio["Ring of Swarming Thought"] = " - |cff9664c8No Prio|r"
loot_prio["Barrage Shoulders"] = " - |cff9664c8No Prio|r"
loot_prio["Breastplate of Annihilation"] = " - |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Cloak of Concentrated Hatred"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfffff569Rogue|r = |cffff7d0aFeral|r = |cfff58cbaRetri|r"
loot_prio["Leggings of Immersion"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of the Unwavering Will"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of the Redeemed Prophecy"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of the Fallen Prophet"] = " - |cff9664c8No Prio|r"
loot_prio["Staff of the Qiraji Prophets"] = " - |cff9664c8No Prio|r"
loot_prio["Hammer of Ji'zhi"] = " - |cff9664c8No Prio|r"
-- Bug Trio:
loot_prio["Guise of the Devourer"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Angelista's Charm"] = " - |cff9664c8No Prio|r"
loot_prio["Robes of the Triumvirate"] = " - |cff9664c8No Prio|r"
loot_prio["Vest of Swift Execution"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Ternary Mantle"] = " - |cff9664c8No Prio|r"
loot_prio["Mantle of Phrenic Power"] = " - |cff9664c8No Prio|r"
loot_prio["Mantle of the Desert Crusade"] = " - |cff9664c8No Prio|r"
loot_prio["Mantle of the Desert's Fury"] = " - |cff9664c8No Prio|r"
loot_prio["Gloves of Ebru"] = " - |cffff7d0aMoonkin|r > |cff77ce5eAll Specs|r"
loot_prio["Ooze-ridden Gauntlets"] = " - |cff9664c8No Prio|r"
loot_prio["Bile-Covered Gauntlets"] = " - |cff9664c8No Prio|r"
loot_prio["Angelista's Touch"] = " - |cff9664c8No Prio|r"
loot_prio["Ukko's Ring of Darkness"] = " - |cff9664c8No Prio|r"
loot_prio["Ring of the Devoured"] = " - |cff9664c8No Prio|r"
loot_prio["Cape of the Trinity"] = " - |cff9664c8No Prio|r"
loot_prio["Triad Girdle"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of the Fallen Hero"] = " - |cff9664c8No Prio|r"
loot_prio["Wand of Qiraji Nobility"] = " - |cffff4f00Core Prio|r * |cffffffff Shadow|r > |cff77ce5eAll Specs|r"
loot_prio["Petrified Scarab"] = " - |cff9664c8No Prio|r"
-- Battleguard Sartura:
loot_prio["Creeping Vine Helm"] = " - |cff9664c8No Prio|r"
loot_prio["Necklace of Purity"] = " - |cff9664c8No Prio|r"
loot_prio["Robes of the Battleguard"] = " - |cff9664c8No Prio|r"
loot_prio["Gauntlets of Steadfast Determination"] = " - |cffff4f00Core Prio|r * |cffc79c6eProt|r = |cfff58cbaProt|r"
loot_prio["Gloves of Enforcement"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Thick Qirajihide Belt"] = " - |cff9664c8No Prio|r"
loot_prio["Leggings of the Festering Swarm"] = " - |cff9664c8No Prio|r"
loot_prio["Legplates of Blazing Light"] = " - |cff9664c8No Prio|r"
loot_prio["Scaled Leggings of Qiraji Fury"] = " - |cff9664c8No Prio|r"
loot_prio["Recomposed Boots"] = " - |cff9664c8No Prio|r"
loot_prio["Silithid Claw"] = " - |cffabd473Hunter|r > |cfffff569Rogue|r = |cffc79c6eWarrior|r"
loot_prio["Sartura's Might"] = " - |cffffffffPriest|r > |cff77ce5eAll Specs|r"
loot_prio["Badge of the Swarmguard"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cffabd473Hunter|r = |cfffff569Rogue|r"
-- Fankriss the Unyielding:
loot_prio["Barbed Choker"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cff0070deEnch|r"
loot_prio["Pauldrons of the Unrelenting"] = " - |cff9664c8No Prio|r"
loot_prio["Mantle of Wicked Revenge"] = " - |cff9664c8No Prio|r"
loot_prio["Silithid Carapace Chestguard"] = " - |cff9664c8No Prio|r"
loot_prio["Robes of the Guardian Saint"] = " - |cff9664c8No Prio|r"
loot_prio["Cloak of Untold Secrets"] = " - |cff9664c8No Prio|r"
loot_prio["Scaled Sand Reaver Leggings"] = " - |cff0070deEnch|r > |cffc79c6eWarrior|r"
loot_prio["Hive Tunneler's Boots"] = " - |cff9664c8No Prio|r"
loot_prio["Barb of the Sand Reaver"] = " - |cffabd473Hunter|r = |cffff7d0aFeral|r"
loot_prio["Ancient Qiraji Ripper"] = " - |cfffff569Rogue|r = |cffc79c6eWarrior|r"
loot_prio["Fetish of the Sand Reaver"] = " - |cff9664c8No Prio|r"
-- Viscidus:
loot_prio["Ring of the Qiraji Fury"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cff0070deEnch|r > |cfffff569Rogue|r > |cfff58cbaPaladin|r"
loot_prio["Gauntlets of Kalimdor"] = " - |cff9664c8No Prio|r"
loot_prio["Slime-coated Leggings"] = " - |cff9664c8No Prio|r"
loot_prio["Sharpened Silithid Femur"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r"
loot_prio["Scarab Brooch"] = " - |cff9664c8No Prio|r"
loot_prio["Gauntlets of the Righteous Champion"] = " - |cff9664c8No Prio|r"
-- Princess Huhuran:
loot_prio["Ring of the Martyr"] = " - |cff9664c8No Prio|r"
loot_prio["Wasphide Gauntlets"] = " - |cff9664c8No Prio|r"
loot_prio["Gloves of the Messiah"] = " - |cff9664c8No Prio|r"
loot_prio["Hive Defiler Wristguards"] = " - |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Cloak of the Golden Hive"] = " - |cffc79c6eProt|r = |cffff7d0aFeral|r"
loot_prio["Huhuran's Stinger"] = " - |cfffff569Rogue|r > |cffc79c6eWarrior|r"
-- Twin Emperors:
loot_prio["Amulet of Vek'nilash"] = " - |cff9482c9Warlock|r = |cff69ccf0Mage|r = |cff0070deElem|r"
loot_prio["Ring of Emperor Vek'lor"] = " - |cff9664c8No Prio|r"
loot_prio["Vek'lor's Gloves of Devastation"] = " - |cffabd473Hunter|r = |cff0070deEnch|r"
loot_prio["Gloves of the Hidden Temple"] = " - |cff9664c8No Prio|r"
loot_prio["Bracelets of Royal Redemption"] = " - |cff9664c8No Prio|r"
loot_prio["Royal Qiraji Belt"] = " - |cffc79c6eProt|r = |cfff58cbaProt|r"
loot_prio["Regenerating Belt of Vek'nilash"] = " - |cff9664c8No Prio|r"
loot_prio["Belt of the Fallen Emperor"] = " - |cff9664c8No Prio|r"
loot_prio["Grasp of the Fallen Emperor"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of Epiphany"] = " - |cffffffffShadow|r > |cff77ce5eAll Specs|r"
loot_prio["Royal Scepter of Vek'lor"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r"
loot_prio["Kalimdor's Revenge"] = " - |cff9664c8No Prio|r"
loot_prio["Qiraji Execution Bracers"] = " - |cff9664c8No Prio|r"
-- Ouro:
loot_prio["Don Rigoberto's Lost Hat"] = " - |cff9664c8No Prio|r"
loot_prio["Burrower Bracers"] = " - |cffffffffShadow|r > |cff77ce5eAll Specs|r"
loot_prio["Larvae of the Great Worm"] = " - |cffabd473Hunter|r = |cfffff569Rogue|r = |cffc79c6eWarrior|r"
loot_prio["Ivonor, Maiden's Mallet"] = " - |cff9664c8No Prio|r"
loot_prio["Jom Gabbar"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfffff569Rogue|r =|cffabd473Hunter|r"
loot_prio["The Burrower's Shell"] = " - |cff9664c8No Prio|r"
loot_prio["Wormhide Boots"] = " - |cff9664c8No Prio|r"
loot_prio["Wormscale Stompers"] = " - |cff9664c8No Prio|r"
loot_prio["Wormhide Protector"] = " - |cff9664c8No Prio|r"
loot_prio["Wormscale Blocker"] = " - |cff9664c8No Prio|r"
loot_prio["Carapace Handguards"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfff58cbaPaladin|r = |cff0070deEnch|r"
loot_prio["Gloves of the Primordial Burrower"] = " - |cffff4f00Core Prio|r * |cfffff569Rogue|r = |cffc79c6eWarrior|r"
-- C'Thun:
loot_prio["Mark of C'Thun"] = " - |cff9664c8Tank|r"
loot_prio["Ring of the Godslayer"] = " - |cffabd473Hunter|r = |cffc79c6eProt|r > |cffff7d0aFeral|r"
loot_prio["Dark Storm Gauntlets"] = " - |cffff4f00Core Prio|r * |cff9482c9Warlock|r = |cff69ccf0Mage|r = |cff0070deElem|r = |cffffffffShadow|r = |cffff7d0aMoonkin|r"
loot_prio["Gauntlets of Annihilation"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Cloak of Clarity"] = " - |cff9664c8No Prio|r"
loot_prio["Cloak of the Devoured"] = " - |cff9482c9Warlock|r = |cff69ccf0Mage|r = |cffffffffShadow|r"
loot_prio["Grasp of the Old God"] = " - |cff9664c8No Prio|r"
loot_prio["Belt of Never-ending Agony"] = " - |cffff4f00Core Prio|r * |cfffff569Rogue|r = |cffff7d0aFeral|r > |cffc79c6eWarrior|r"
loot_prio["Eyestalk Waist Cord"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r > |cffffffffShadow|r"
loot_prio["Scepter of the False Prophet"] = " - |cffff4f00Core Prio|r *"
loot_prio["Death's Sting"] = " - |cfffff569Rogue|r > |cffc79c6eProt|r"
loot_prio["Dark Edge of Insanity"] = " - |cff9664c8No Prio|r"
loot_prio["Vanquished Tentacle of C'Thun"] = " - |cff9664c8No Prio|r"
loot_prio["Yshgo'lar, Cowl of Fanatical Devotion"] = " - |cffff4f00Core Prio|r * |cff9482c9Warlock|r = |cff0070deElem|r = |cffff7d0aMoonkin|r = |cff69ccf0Mage|r"
loot_prio["Remnants of an Old God"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Eye of C'Thun"] = " - |cff9664c8No Prio|r"
-- Trash Mobs (AQ40):
loot_prio["Gloves of the Redeemed Prophecy"] = " - |cff9664c8No Prio|r"
loot_prio["Ritssyn's Ring of Chaos"] = " - |cff69ccf0Mage|r > |cff77ce5eAll Specs|r"
loot_prio["Gloves of the Immortal"] = " - |cff9664c8No Prio|r"
loot_prio["Garb of Royal Ascension"] = " - |cff9482c9Warlock|r > |cff77ce5eAll Specs|r"
loot_prio["Anubisath Warhammer"] = " - |cff9664c8No Prio|r"
loot_prio["Neretzek, The Blood Drinker"] = " - |cff9664c8No Prio|r"
loot_prio["Shard of the Fallen Star"] = " - |cffff4f00Core Prio|r *"
loot_prio["Gloves of the Fallen Prophet"] = " - |cff9664c8No Prio|r"
loot_prio["Imperial Qiraji Armaments"] = " - |cff9664c8No Prio|r"
loot_prio["Imperial Qiraji Regalia"] = " - |cff9664c8No Prio|r"
-- < Emerald Sanctum >
-- Erennius:
loot_prio["Claw of Erennius"] = " - |cff9664c8No Prio|r"
-- Solnius the Awakener:
loot_prio["Robe of the Dreamways"] = " - |cff9664c8No Prio|r"
loot_prio["Sandals of Lucidity"] = " - |cff9664c8No Prio|r"
loot_prio["Talonwind Gauntlets"] = " - |cff9664c8No Prio|r"
loot_prio["Ancient Jade Leggings"] = " - |cff9664c8No Prio|r"
loot_prio["Aspect of Seradane"] = " - |cff9664c8No Prio|r"
loot_prio["Mallet of the Awakening"] = " - |cff9664c8No Prio|r"
loot_prio["Scaleshield of Emerald Flight"] = " - |cff9664c8No Prio|r"
loot_prio["Ring of Nature's Duality"] = " - |cff0070deShaman|r = |cffff7d0aDruid|r = |cfff58cbaHoly|r"
loot_prio["Shard of Nightmare"] = " - |cff9482c9Warlock|r = |cff69ccf0Mage|r = |cffffffffShadow|r = |cffff7d0aMoonkin|r"
loot_prio["Veil of Nightmare"] = " - |cff9664c8No Prio|r"
loot_prio["Sanctum Bark Wraps"] = " - |cff9664c8No Prio|r"
loot_prio["Mantle of the Wakener"] = " - |cff9664c8No Prio|r"
loot_prio["Jadestone Helmet"] = " - |cff9664c8No Prio|r"
loot_prio["Axe of Dormant Slumber"] = " - |cff9664c8No Prio|r"
loot_prio["Staff of the Dreamer"] = " - |cff9664c8No Prio|r"
loot_prio["Head of Solnius"] = " - |cff9664c8No Prio|r"
-- Favor of Erennius (Chest):
loot_prio["Naturecaller's Tunic"] = " - |cffff7d0aMoonkin|r > |cff77ce5eAll Specs|r"
loot_prio["Choker of the Emerald Lord"] = " - |cffff4f00Core Prio|r *"
loot_prio["Breath of Solnius"] = " - |cffff4f00Core Prio|r *"
loot_prio["Crystal Sword of the Blossom"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Nature's Call"] = " - |cffabd473Hunter|r > |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Jadestone Protector"] = " - |cfff58cbaProt|r = |cff0070deEnch|r"
-- Trash Mobs (ES):
loot_prio["Verdant Dreamer's Boots"] = " - |cff9664c8No Prio|r"
loot_prio["Infused Wildthorn Bracers"] = " - |cff9664c8No Prio|r"
loot_prio["Sleeper's Ring"] = " - |cff9664c8No Prio|r"
loot_prio["Lasher's Whip"] = " - |cff9664c8No Prio|r"
loot_prio["Corrupted Reed"] = " - |cff9664c8No Prio|r"
loot_prio["Lucid Nightmare"] = " - |cff9482c9Warlock|r > |cff77ce5eAll Specs|r"
loot_prio["Emerald Rod"] = " - |cff9664c8No Prio|r"
loot_prio["Nature's Gift"] = " - |cff9664c8No Prio|r"
loot_prio["Dream Frog"] = " - |cff9664c8Council|r"
-- < Naxxramas >
-- Anub'Rekhan:
loot_prio["Cryptfiend Silk Cloak"] = " - |cffff7d0aFeral|r = |cffc79c6eProt|r = |cfff58cbaProt|r = |cff0070deEnch|r"
loot_prio["Gem of Nerubis"] = " - |cff9664c8No Prio|r"
loot_prio["Band of Unanswered Prayers"] = " - |cff9664c8No Prio|r"
loot_prio["Wristguards of Vengeance"] = " - |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
loot_prio["Touch of Frost"] = " - |cff9664c8No Prio|r"
-- Grand Widow Faerlina:
loot_prio["Malice Stone Pendant"] = " - |cff9664c8No Prio|r"
loot_prio["The Widow's Embrace"] = " - |cff9664c8No Prio|r"
loot_prio["Widow's Remorse"] = " - |cff9664c8No Prio|r"
loot_prio["Polar Shoulder Pads"] = " - |cff9664c8No Prio|r"
loot_prio["Icebane Pauldrons"] = " - |cff9664c8No Prio|r"
-- Maexxna:
loot_prio["Kiss of the Spider"] = " - |cffff4f00Core Prio|r * |cff77ce5eMelee DPS|r = |cfff58cbaAP Retri|r = |cfff58cbaAirisviel|r"
loot_prio["Wraith Blade"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r = |cff9482c9Warlock|r > |cfff58cbaProt|r"
loot_prio["Pendant of Forgotten Names"] = " - |cff9664c8No Prio|r"
loot_prio["Maexxna's Fang"] = " - |cff9664c8No Prio|r"
loot_prio["Crystal Webbed Robe"] = " - |cffffffffShadow|r > |cff77ce5eAll Specs|r"
-- Noth the Plaguebringer:
loot_prio["Cloak of the Scourge"] = " - |cff9664c8No Prio|r"
loot_prio["Band of the Inevitable"] = " - |cff9664c8No Prio|r"
loot_prio["Hatchet of Sundered Bone"] = " - |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
loot_prio["Noth's Frigid Heart"] = " - |cff9664c8No Prio|r"
loot_prio["Hailstone Band"] = " - |cff9664c8No Prio|r"
-- Heigan the Unclean:
loot_prio["Necklace of Necropsy"] = " - |cff9664c8No Prio|r"
loot_prio["Preceptor's Hat"] = " - |cffffffffShadow|r > |cff77ce5eAll Specs|r"
loot_prio["Legplates of Carnage"] = " - |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Icy Scale Coif"] = " - |cff9664c8No Prio|r"
loot_prio["Icebane Helmet"] = " - |cff9664c8No Prio|r"
-- Loatheb:
loot_prio["Band of Unnatural Forces"] = " - |cffff4f00Core Prio|r * |cfffff569Rogue|r = |cffc79c6eWarrior|r = |cffff7d0aFeral|r = |cfff58cbaAP Retri|r"
loot_prio["Ring of Spiritual Fervor"] = " - |cff9664c8No Prio|r"
loot_prio["Loatheb's Reflection"] = " - |cff9664c8No Prio|r"
loot_prio["Brimstone Staff"] = " - |cff9664c8No Prio|r"
loot_prio["The Eye of Nerub"] = " - |cffabd473Hunter|r = |cffff7d0aFeral|r"
-- Instructor Razuvious:
loot_prio["Wand of the Whispering Dead"] = " - |cff9664c8No Prio|r"
loot_prio["Iblis, Blade of the Fallen Seraph"] = " - |cfffff569Rogue|r = |cffc79c6eWarrior|r"
loot_prio["Signet of the Fallen Defender"] = " - |cffc79c6eProt|r = |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Girdle of the Mentor"] = " - |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Veil of Eclipse"] = " - |cff9482c9Warlock|r = |cff0070deElem|r"
-- Gothik the Harvester:
loot_prio["Boots of Displacement"] = " - |cff9664c8No Prio|r"
loot_prio["The Soul Harvester's Bindings"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cff0070deElem|r > |cffff7d0aMoonkin|r"
loot_prio["Sadist's Collar"] = " - |cff9664c8No Prio|r"
loot_prio["Polar Helmet"] = " - |cff9664c8No Prio|r"
loot_prio["Glacial Headdress"] = " - |cff9664c8No Prio|r"
-- Four Horsemen (Chest):
loot_prio["Leggings of Apocalypse"] = " - |cffc79c6eWarrior|r = |cffff7d0aFeral|r"
loot_prio["Soulstring"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r = |cffabd473Hunter|r"
loot_prio["Maul of the Redeemed Crusader"] = " - |cff9664c8No Prio|r"
loot_prio["Corrupted Ashbringer"] = " - |cfff58cbaRetri|r > |cff77ce5eAll Specs|r"
loot_prio["Seal of the Damned"] = " - |cffff4f00Core Prio|r * |cff9482c9Warlock|r = |cffff7d0aMoonkin|r"
loot_prio["Warmth of Forgiveness"] = " - |cff9664c8No Prio|r"
-- Patchwerk:
loot_prio["Severance"] = " - |cff0070deEnch|r = |cffc79c6eWarrior|r"
loot_prio["Cloak of Suturing"] = " - |cffff4f00Core Prio|r *"
loot_prio["Wand of Fates"] = " - |cff9482c9Warlock|r > |cff69ccf0Mage|r"
loot_prio["Band of Reanimation"] = " - |cffabd473Hunter|r > |cff77ce5eAll Specs|r"
loot_prio["The Plague Bearer"] = " - |cff9664c8No Prio|r"
-- Grobbulus:
loot_prio["Toxin Injector"] = " - |cff9664c8No Prio|r"
loot_prio["Midnight Haze"] = " - |cff9664c8No Prio|r"
loot_prio["The End of Dreams"] = " - |cff9664c8No Prio|r"
loot_prio["Glacial Mantle"] = " - |cff9664c8No Prio|r"
loot_prio["Icy Scale Spaulders"] = " - |cff9664c8No Prio|r"
-- Gluth:
loot_prio["Claymore of Unholy Might"] = " - |cff9664c8No Prio|r"
loot_prio["Death's Bargain"] = " - |cff9664c8No Prio|r"
loot_prio["Digested Hand of Power"] = " - |cff9664c8No Prio|r"
loot_prio["Gluth's Missing Collar"] = " - |cfff58cbaProt|r > |cff77ce5eAll Specs|r"
loot_prio["Rime Covered Mantle"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r > |cff0070deElem|r = |cffff7d0aMoonkin|r = |cff9482c9Warlock|r"
-- Thaddius:
loot_prio["Eye of Diminution"] = " - |cff0070deElem|r > |cff77ce5eAll Specs|r"
loot_prio["Leggings of Polarity"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cff0070deElem|r = |cffff7d0aMoonkin|r > |cffffffffShadow|r"
loot_prio["Plated Abomination Ribcage"] = " - |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
loot_prio["Spire of Twilight"] = " - |cff9664c8No Prio|r"
loot_prio["The Castigator"] = " - |cffc79c6eWarrior|r > |cfffff569Rogue|r = |cff0070deEnch|r"
-- Sapphiron:
loot_prio["Eye of the Dead"] = " - |cffff4f00Core Prio|r *"
loot_prio["Glyph of Deflection"] = " - |cff9664c8No Prio|r"
loot_prio["Slayer's Crest"] = " - |cffff4f00Core Prio|r * |cff9664c8Melee DPS|r = |cfff58cbaAP Retri|r"
loot_prio["Claw of the Frost Wyrm"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Cloak of the Necropolis"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cff0070deElem|r > |cfff58cbaHoly|r"
loot_prio["Shroud of Dominion"] = " - |cffff4f00Core Prio|r * |cff9664c8Melee DPS|r = |cfff58cbaAP Retri|r"
loot_prio["Sapphiron's Left Eye"] = " - |cffff4f00Core Prio|r *"
loot_prio["Sapphiron's Right Eye"] = " - |cff9664c8No Prio|r"
loot_prio["The Restrained Essence of Sapphiron"] = " - |cffff4f00Core Prio|r * |cff9664c8Casters|r = |cfff58cbaSpell Retri/Prot|r"
loot_prio["The Face of Death"] = " - |cffff4f00Core Prio|r * |cffc79c6eProt|r = |cfff58cbaProt|r"
loot_prio["Fortitude of the Scourge"] = " - |cff9664c8No Prio|r"
loot_prio["Power of the Scourge"] = " - |cff9664c8No Prio|r"
loot_prio["Resilience of the Scourge"] = " - |cff9664c8No Prio|r"
loot_prio["Might of the Scourge"] = " - |cff9664c8No Prio|r"
-- Kel'Thuzad:
loot_prio["Stormrage's Talisman of Seething"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cff0070deEnch|r = |cfff58cbaAP Retri|r > |cfffff569Rogue|r"
loot_prio["Nerubian Slavemaker"] = " - |cffff4f00Core Prio|r * |cffabd473Hunter|r = |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Gressil, Dawn of Ruin"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Doomfinger"] = " - |cffff4f00Core Prio|r * |cff69ccf0Mage|r > |cff9482c9Warlock|r"
loot_prio["Gem of Trapped Innocents"] = " - |cffff4f00Core Prio|r * |cff9482c9Warlock|r = |cff69ccf0Mage|r = |cffff7d0aMoonkin|r > |cfff58cbaHoly|r"
loot_prio["Hammer of the Twisting Nether"] = " - |cffff4f00Core Prio|r *"
loot_prio["Kingsfall"] = " - |cffff4f00Core Prio|r * |cfffff569Rogue|r = |cffabd473Hunter|r = |cffc79c6eWarrior|r"
loot_prio["Might of Menethil"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfff58cbaRetri|r = |cffff7d0aFeral|r = |cff0070deEnch|r"
loot_prio["Shield of Condemnation"] = " - |cffff4f00Core Prio|r"
loot_prio["Soulseeker"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cffffffffShadow|r = |cff0070deElem|r = |cffff7d0aMoonkin|r"
loot_prio["The Hungering Cold"] = " - |cffff4f00Core Prio|r * |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["The Phylactery of Kel'Thuzad"] = " - |cff9664c8No Prio|r"
-- Trash Mobs (Naxx):
loot_prio["Ghoul Skin Tunic"] = " - |cff9664c8No Prio|r"
loot_prio["Ring of the Eternal Flame"] = " - |cff9664c8No Prio|r"
loot_prio["Stygian Buckler"] = " - |cff9664c8No Prio|r"
loot_prio["Harbinger of Doom"] = " - |cff9664c8No Prio|r"
loot_prio["Misplaced Servo Arm"] = " - |cff9664c8No Prio|r"
-- < Karazhan >
-- Keeper Gnarlmoon:
loot_prio["Ley-attuned Choker"] = " - |cff9664c8No Prio|r"
loot_prio["Manadrenched Feather Slippers"] = " - |cff9664c8No Prio|r"
loot_prio["Torn Wings of Midnight"] = " - |cff9664c8No Prio|r"
loot_prio["Crite's Holy Hands"] = " - |cffffffffHoly|r = |cffff7d0aResto|r > |cff77ce5eAll Specs|r"
loot_prio["Ravenkeeper’s Frenzied Embrace"] = " - |cffff7d0aFeral|r = |cff0070deEnch|r = |cffabd473Hunter|r"
loot_prio["Bloodmoon, Sickle of the Murderous Flight"] = " - |cfffff569Rogue|r = |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
loot_prio["Idol of Laceration"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Crown of the Wildpack"] = " - |cff0070deEnch|r = |cffabd473Hunter|r"
-- Ley-Watcher Incantagos:
loot_prio["Magispark Leggings"] = " - |cff9664c8No Prio|r"
loot_prio["Jewel of Wild Magics"] = " - |cff9664c8No Prio|r"
loot_prio["Scaleshield of Azure Flight"] = " - |cff0070deElem|r > |cff77ce5eAll Specs|r"
loot_prio["Loop of Infused Renewal"] = " - |cff9664c8No Prio|r"
loot_prio["Magehunter Belt"] = " - |cff9664c8No Prio|r"
loot_prio["Bands of the Surgebreaker"] = " - |cffff7d0aFeral|r > |cfffff569Rogue|r"
loot_prio["Leysteel Legplates"] = " - |cfff58cbaProt|r > |cff77ce5eAll Specs|r"
loot_prio["Choker of Terminal Arcanum"] = " - |cffff7d0aFeral|r = |cffc79c6eWarrior|r = |cfffff569Rogue|r"
loot_prio["Enchanted Amethyst"] = " - |cff9664c8No Prio|r"
-- Anomalus:
loot_prio["Manahide Slippers"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Cloak of the Bloody Ravager"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Phase-shifting Crossbow"] = " - |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
loot_prio["Branch of Resolute Defense"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Remains of Overwhelming Power"] = " - |cff69ccf0Mage|r = |cff0070deElem|r = |cff9482c9Warlock|r > |cfff58cbaSpell/Prot|r"
loot_prio["Choker of Chromatic Power"] = " - |cfff58cbaProt|r > |cff77ce5eAll Specs|r"
loot_prio["Gloves of Nourishment"] = " - |cffff7d0aResto|r = |cff0070deResto|r > |cff77ce5eAll Specs|r"
loot_prio["Bindings of Contained Magic"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cffffffffShadow|r"
-- Echo of Medivh:
loot_prio["Medivh's Hindsight"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cff0070deElem|r = |cffff7d0aMoonkin|r = |cffffffffSmite|r"
loot_prio["Gloves of Leyline Convergence"] = " - |cff9664c8No Prio|r"
loot_prio["Eye of Dormant Corruption"] = " - |cffffffffShadow|r = |cff9482c9Afli|r"
loot_prio["Pendant of Forgiven Mistakes"] = " - |cff9664c8No Prio|r"
loot_prio["Dreadslayer Shoulderblades"] = " - |cffc79c6eWarrior|r > |cfff58cbaAP Retri|r"
loot_prio["Legwraps of Meticulous Planning"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Libram of the Eternal Tower"] = " - |cfff58cbaRetri Prio|r"
loot_prio["Forgotten Raven's Mallet"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
-- King (Chess Fight):
loot_prio["Dragonclaw Gauntlets"] = " - |cff9664c8No Prio|r"
loot_prio["Checkmate"] = " - |cff0070deEnch|r = |cffc79c6eWarrior|r = |cfff58cbaRetri|r > |cff77ce5eAll Specs|r"
loot_prio["King's Edict"] = " - |cff9664c8Tank|r"
loot_prio["Insomnius' Retribution"] = " - |cff0070deElem|r > |cfff58cbaSpell/Prot|r"
loot_prio["Royal Seal of Greymane"] = " - |cff9482c9Warlock|r > |cff77ce5eAll Specs|r"
loot_prio["Pawn's Advance"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Bishop's Reverence"] = " - |cff9664c8No Prio|r"
loot_prio["Chain-Cloak of the Rookguard"] = " - |cfff58cbaProt|r = |cff0070deEnch|r"
-- Sanv Tas'dal:
loot_prio["Dreadslayer Horns"] = " - |cffc79c6eWarrior|r > |cfff58cbaAP Retri|r"
loot_prio["Riftcarver's Implement"] = " - |cfffff569Rogue|r = |cffc79c6eWarrior|r"
loot_prio["Raka'shishi, Spear of the Adrift Hunt"] = " - |cffc79c6eWarrior|r = |cffabd473Hunter|r = |cffff7d0aFeral|r = |cfff58cbaRetri|r"
loot_prio["Girdle of the Faded Primals"] = " - |cff0070deElem|r > |cfff58cbaSpell Retri|r"
loot_prio["Kum'isha's Tattered Drape"] = " - |cffffffffShadow|r = |cff9482c9Afli|r = |cff69ccf0Mage|r = |cffff7d0aMoonkin|r = |cff0070deElem|r = |cfff58cbaSpell Retri|r"
loot_prio["Forgotten Hide Helm"] = " - |cffff7d0aFeral|r = |cff0070deEnch|r = |cffc79c6eWarrior|r"
loot_prio["Totem of Broken Earth"] = " - |cff0070deEnch Prio|r"
-- Rupturan the Broken:
loot_prio["Al'Kazeth, Claw of Ruptured Elements"] = " - |cff0070deElem|r > |cff77ce5eAll Specs|r"
loot_prio["Bulwark of Enduring Earth"] = " - |cffc79c6eProt|r = |cfff58cbaProt|r"
loot_prio["Earthquake Leggings"] = " - |cff0070deEnch|r = |cfff58cbaRetri|r"
loot_prio["Loop of Hardened Slate"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Pure Jewel of Draenor"] = " - |cff9664c8No Prio|r"
loot_prio["Handwraps of Dead Winds"] = " - |cffff7d0aFeral|r > |cff77ce5eAll Specs|r"
loot_prio["Mantle of the Drifting Stars"] = " - |cff0070deElem|r = |cffff7d0aMoonkin|r"
-- Kruul:
loot_prio["Hellflame"] = " - |cffffffffShadow|r = |cff9482c9Afli|r"
loot_prio["Shar'tateth, the Shattered Edge"] = " - |cffc79c6eWingcrow|r > |cffc79c6eWarrior|r = |cff0070deEnch|r = |cffabd473Surv|r > |cfff58cbaRetri|r"
loot_prio["Comet Signaller"] = " - |cffffffffShadow|r > |cff77ce5eAll Specs|r"
loot_prio["Desecration"] = " - |cfff58cbaProt|r > |cff77ce5eAll Specs|r"
loot_prio["Wristwraps of Exiled Radiance"] = " - |cff9664c8No Prio|r"
loot_prio["Shieldrender Talisman"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r = |cffff7d0aFeral|r = |cffabd473Surv|r"
loot_prio["Pendant of Purified Demon's Blood"] = " - |cffc79c6eProt|r > |cff77ce5eAll Specs|r"
loot_prio["Worldbreaker Girdle"] = " - |cffc79c6eWarrior|r > |cfff58cbaPaladin|r"
loot_prio["Fragments of Aldrach"] = " - |cfffff569Rogue|r = |cffabd473Surv|r"
-- Mephistroth:
loot_prio["Turalyon's Hope"] = " - |cfff58cbaRetri|r > |cff77ce5eAll Specs|r"
loot_prio["Mephistroth's Cunning"] = " - |cfffff569Rogue|r = |cffabd473Hunter|r = |cffff7d0aFeral|r = |cffc79c6eWarrior|r = |cff0070deEnch|r"
loot_prio["Netherwrought Bracers"] = " - |cffc79c6eWarrior|r > |cfff58cbaAP Retri|r"
loot_prio["Sash of the Grand Betrayal"] = " - |cfffff569Rogue|r = |cffff7d0aFeral|r > |cff0070deEnch|r = |cffc79c6eWarrior|r"
loot_prio["Tunic of Demonic Deception"] = " - |cffc79c6eWarrior|r > |cfffff569Rogue|r > |cffff7d0aFeral|r"
loot_prio["Thunderfall, Stormhammer of the Chief Thane"] = " - |cffc79c6eWarrior|r = |cfffff569Rogue|r > |cff77ce5eAll Specs|r"
loot_prio["Rain of Spiders"] = " - |cffabd473Hunter|r"
loot_prio["Kirel'narak, the Death Sentence"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cffff7d0aMoonkin|r = |cffffffffShadow|r > |cff0070deElem|r"
loot_prio["Nethraka, Wing of Oblivion"] = " - |cff9664c8No Prio|r"
loot_prio["Forgotten Hide Pauldrons"] = " - |cffff7d0aResto|r > |cff77ce5eAll Specs|r"
loot_prio["Censer of Soulwarding"] = " - |cffffffffHoly|r > |cff77ce5eAll Specs|r"
loot_prio["Cloak of Rapid Regeneration"] = " - |cff9664c8No Prio|r"
loot_prio["Khadgar's Guidance"] = " - |cff69ccf0Mage|r = |cff0070deElem|r = |cff9482c9Warlock|r = |cffff7d0aMoonkin|r"
loot_prio["Memory of the Last Guardian"] = " - |cff69ccf0Mage|r = |cff9482c9Warlock|r = |cffff7d0aMoonkin|r = |cffffffffShadow|r > |cff0070deElem|r"
loot_prio["Heart of Mephistroth"] = " - |cff9664c8No Prio|r"
-- Trash Mobs (Kara40):
loot_prio["Slivers of Nullification"] = " - |cff9664c8No Prio|r"
loot_prio["The End of All Ambitions"] = " - |cff9664c8No Prio|r"
loot_prio["Ques' Gauntlets of Precision"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of Elemental Fury"] = " - |cff0070deElem|r"
loot_prio["Gauntlets of Elemental Fury"] = " - |cff9664c8No Prio|r"
loot_prio["Boots of the Grand Crusader"] = " - |cfff58cbaRetri|r"
loot_prio["Gauntlets of the Grand Crusader"] = " - |cfff58cbaRetri|r"
loot_prio["Dragunovi's Sash of Domination"] = " - |cff9482c9Warlock|r = |cffffffffShadow|r"
loot_prio["Ring of Holy Light"] = " - |cffffffffSmite|r"
loot_prio["Brand of Karazhan"] = " - |cffc79c6eWarrior|r > |cff77ce5eAll Specs|r"
